default_config:

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
input_datetime: !include input_datetimes.yaml
utility_meter: !include utility_meter.yaml

http:
  server_port: 8123
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.20.0.3
    - 172.20.0.4
    - 127.0.0.1
    - ::1
  ip_ban_enabled: true
  login_attempts_threshold: 5
  
